//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoNomina2019
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion_Empleados_Salarios_Totales
    {
        public int Liquidacion_Id { get; set; }
        public int Empleado_Id { get; set; }
        public int SalarioTotal { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Liquidacion_Mensual Liquidacion_Mensual { get; set; }
    }
}
